create extension if not exists vector with schema extensions;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.business_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text,
  address text,
  email text,
  phone text,
  tax_id text,
  logo_path text,
  default_currency text not null default 'USD',
  default_tax_pct double precision not null default 0.0,
  payment_terms text not null default 'Net 30',
  bank_name text,
  account_name text,
  account_number text,
  routing_number text,
  payment_notes text,
  default_email_subject varchar(200) not null default 'Invoice {invoice_number}',
  default_email_message text not null default E'Hello {client_name},\n\nPlease find invoice {invoice_number} attached.\n\nBest,\n{business_name}',
  onboarding_completed_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint uq_business_settings_user_id unique (user_id),
  constraint ck_business_settings_email_subject_not_blank check (length(btrim(default_email_subject)) > 0),
  constraint ck_business_settings_email_message_not_blank check (length(btrim(default_email_message)) > 0),
  constraint ck_business_settings_email_message_length check (char_length(default_email_message) <= 5000)
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  client_code text,
  address text,
  email text,
  phone text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_clients_user_id_client_code unique (user_id, client_code)
);

create table if not exists public.client_addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  label text,
  address text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.catalog_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  description text not null,
  unit_price double precision not null default 0.0,
  unit text not null default 'item',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoice_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  client_id bigint references public.clients(id) on delete set null,
  client_invoice_sequence integer,
  filename text not null,
  file_path text not null,
  storage_path text,
  source text not null,
  invoice_number text,
  client_name text,
  issue_date text,
  grand_total double precision,
  currency text not null default 'USD',
  rag_doc_id text,
  status text not null default 'draft',
  invoice_json text,
  created_at timestamptz not null default now(),
  constraint valid_source check (source in ('uploaded', 'generated')),
  constraint uq_invoice_records_user_client_sequence unique (user_id, client_id, client_invoice_sequence)
);

create table if not exists public.invoice_embeddings (
  id bigint generated by default as identity primary key,
  doc_id uuid not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  invoice_record_id bigint not null references public.invoice_records(id) on delete cascade,
  filename text not null,
  chunk_index integer not null,
  content text not null,
  embedding extensions.vector(1536) not null,
  created_at timestamptz not null default now(),
  constraint uq_invoice_embeddings_doc_chunk unique (doc_id, chunk_index)
);

create table if not exists public.invoice_emails (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  invoice_record_id bigint not null references public.invoice_records(id) on delete cascade,
  recipient_email text not null,
  cc_email text,
  subject text not null,
  message_body text not null,
  status text not null default 'pending',
  provider text not null default 'smtp',
  provider_message_id text,
  idempotency_key varchar(128),
  request_fingerprint varchar(64),
  attempt_count integer not null default 0,
  attempt_token varchar(36),
  lease_expires_at timestamptz,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  constraint uq_invoice_emails_user_idempotency unique (user_id, idempotency_key)
);

create table if not exists public.security_events (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type varchar(64) not null,
  outcome varchar(16) not null constraint ck_security_events_outcome check (outcome in ('allowed', 'blocked')),
  request_id varchar(128),
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  plan varchar(32) not null default 'free',
  status varchar(32) not null default 'free',
  stripe_customer_id varchar(255),
  stripe_subscription_id varchar(255),
  stripe_price_id varchar(255),
  superseded_subscription_ids text[] not null default '{}'::text[],
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  last_event_created_at bigint,
  checkout_idempotency_key varchar(64),
  checkout_idempotency_created_at timestamptz,
  checkout_session_id varchar(255),
  checkout_session_expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_subscriptions_plan check (plan in ('free', 'pro')),
  constraint uq_subscriptions_user_id unique (user_id),
  constraint uq_subscriptions_customer unique (stripe_customer_id),
  constraint uq_subscriptions_subscription unique (stripe_subscription_id)
);

create table if not exists public.stripe_webhook_events (
  event_id varchar(255) primary key,
  event_type varchar(255) not null,
  event_created_at bigint not null,
  processed_at timestamptz not null default now()
);

create index if not exists ix_profiles_email on public.profiles(email);
create index if not exists ix_business_settings_user_id on public.business_settings(user_id);
create index if not exists ix_clients_user_id on public.clients(user_id);
create index if not exists ix_clients_name on public.clients(name);
create index if not exists ix_clients_client_code on public.clients(client_code);
create index if not exists ix_client_addresses_client_id on public.client_addresses(client_id);
create index if not exists ix_client_addresses_user_id on public.client_addresses(user_id);
create index if not exists ix_catalog_items_user_id on public.catalog_items(user_id);
create index if not exists ix_catalog_items_description on public.catalog_items(description);
create index if not exists ix_invoice_records_user_id on public.invoice_records(user_id);
create index if not exists ix_invoice_records_client_id on public.invoice_records(client_id);
create index if not exists ix_invoice_records_invoice_number on public.invoice_records(invoice_number);
create index if not exists ix_invoice_records_client_name on public.invoice_records(client_name);
create index if not exists ix_invoice_embeddings_user_id on public.invoice_embeddings(user_id);
create index if not exists ix_invoice_embeddings_record_id on public.invoice_embeddings(invoice_record_id);
create index if not exists ix_invoice_embeddings_embedding_hnsw
  on public.invoice_embeddings using hnsw (embedding vector_cosine_ops);
create index if not exists ix_invoice_emails_user_id on public.invoice_emails(user_id);
create index if not exists ix_invoice_emails_record_id on public.invoice_emails(invoice_record_id);
create index if not exists ix_security_events_rate_window
  on public.security_events(user_id, event_type, created_at);
create unique index if not exists ix_subscriptions_user_id on public.subscriptions(user_id);

grant select, insert, update, delete on table
  public.profiles,
  public.business_settings,
  public.clients,
  public.client_addresses,
  public.catalog_items,
  public.invoice_records,
  public.invoice_embeddings,
  public.invoice_emails
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant select on table public.security_events to authenticated;
grant select on table public.subscriptions to authenticated;

alter table public.profiles enable row level security;
alter table public.business_settings enable row level security;
alter table public.clients enable row level security;
alter table public.client_addresses enable row level security;
alter table public.catalog_items enable row level security;
alter table public.invoice_records enable row level security;
alter table public.invoice_embeddings enable row level security;
alter table public.invoice_emails enable row level security;
alter table public.security_events enable row level security;
alter table public.security_events force row level security;
alter table public.subscriptions enable row level security;
alter table public.subscriptions force row level security;
alter table public.stripe_webhook_events enable row level security;
alter table public.stripe_webhook_events force row level security;

drop policy if exists "profiles owner select" on public.profiles;
drop policy if exists "profiles owner insert" on public.profiles;
drop policy if exists "profiles owner update" on public.profiles;
drop policy if exists "profiles owner delete" on public.profiles;
create policy "profiles owner select" on public.profiles for select to authenticated using (id = auth.uid());
create policy "profiles owner insert" on public.profiles for insert to authenticated with check (id = auth.uid());
create policy "profiles owner update" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "profiles owner delete" on public.profiles for delete to authenticated using (id = auth.uid());

drop policy if exists "business settings owner all" on public.business_settings;
create policy "business settings owner all" on public.business_settings for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "clients owner all" on public.clients;
create policy "clients owner all" on public.clients for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "client addresses owner select" on public.client_addresses;
drop policy if exists "client addresses owner insert" on public.client_addresses;
drop policy if exists "client addresses owner update" on public.client_addresses;
drop policy if exists "client addresses owner delete" on public.client_addresses;
create policy "client addresses owner select" on public.client_addresses for select to authenticated
  using (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()));
create policy "client addresses owner insert" on public.client_addresses for insert to authenticated
  with check (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()));
create policy "client addresses owner update" on public.client_addresses for update to authenticated
  using (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()))
  with check (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()));
create policy "client addresses owner delete" on public.client_addresses for delete to authenticated
  using (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()));

drop policy if exists "catalog items owner all" on public.catalog_items;
create policy "catalog items owner all" on public.catalog_items for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "invoice records owner all" on public.invoice_records;
create policy "invoice records owner all" on public.invoice_records for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "invoice embeddings owner all" on public.invoice_embeddings;
create policy "invoice embeddings owner all" on public.invoice_embeddings for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "invoice emails owner all" on public.invoice_emails;
create policy "invoice emails owner all" on public.invoice_emails for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists security_events_owner on public.security_events;
create policy security_events_owner on public.security_events for select to authenticated
  using (user_id = auth.uid());

drop policy if exists "subscriptions owner select" on public.subscriptions;
create policy "subscriptions owner select" on public.subscriptions for select to authenticated
  using (user_id = auth.uid());

insert into storage.buckets (id, name, public)
values ('invoices', 'invoices', false)
on conflict (id) do update set public = excluded.public;

drop policy if exists "invoice objects owner select" on storage.objects;
drop policy if exists "invoice objects owner insert" on storage.objects;
drop policy if exists "invoice objects owner update" on storage.objects;
drop policy if exists "invoice objects owner delete" on storage.objects;
create policy "invoice objects owner select" on storage.objects for select to authenticated
  using (bucket_id = 'invoices' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "invoice objects owner insert" on storage.objects for insert to authenticated
  with check (bucket_id = 'invoices' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "invoice objects owner update" on storage.objects for update to authenticated
  using (bucket_id = 'invoices' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'invoices' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "invoice objects owner delete" on storage.objects for delete to authenticated
  using (bucket_id = 'invoices' and (storage.foldername(name))[1] = auth.uid()::text);
