"""Reconstructs the database shape that existed before Alembic was adopted.

Deployments created by the old startup DDL predate per-client invoice
numbering, the pgvector move, and email history. Migration tests build this
shape so the upgrade path is proven against a realistic starting point rather
than against an empty database.

This mirrors revision ``0001_baseline`` and must be kept in step with it.
"""

from __future__ import annotations

import asyncpg

from tests.support.postgres import asyncpg_dsn

LEGACY_SCHEMA_SQL = """
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.business_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text,
  address text,
  email text,
  phone text,
  tax_id text,
  logo_path text,
  default_currency text not null default 'USD',
  default_tax_pct double precision not null default 0.0,
  payment_terms text not null default 'Net 30',
  bank_name text,
  account_name text,
  account_number text,
  routing_number text,
  payment_notes text,
  updated_at timestamptz not null default now(),
  constraint uq_business_settings_user_id unique (user_id)
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  address text,
  email text,
  phone text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.client_addresses (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  label text,
  address text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.catalog_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  description text not null,
  unit_price double precision not null default 0.0,
  unit text not null default 'item',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoice_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  filename text not null,
  file_path text not null,
  source text not null,
  invoice_number text,
  client_name text,
  issue_date text,
  grand_total double precision,
  currency text not null default 'USD',
  chroma_doc_id text,
  status text not null default 'draft',
  invoice_json text,
  created_at timestamptz not null default now(),
  constraint valid_source check (source in ('uploaded', 'generated'))
);

create index if not exists ix_profiles_email on public.profiles(email);
create index if not exists ix_business_settings_user_id on public.business_settings(user_id);
create index if not exists ix_clients_user_id on public.clients(user_id);
create index if not exists ix_clients_name on public.clients(name);
create index if not exists ix_client_addresses_client_id on public.client_addresses(client_id);
create index if not exists ix_catalog_items_user_id on public.catalog_items(user_id);
create index if not exists ix_catalog_items_description on public.catalog_items(description);
create index if not exists ix_invoice_records_user_id on public.invoice_records(user_id);
create index if not exists ix_invoice_records_invoice_number on public.invoice_records(invoice_number);
create index if not exists ix_invoice_records_client_name on public.invoice_records(client_name);

grant select, insert, update, delete on table
  public.profiles,
  public.business_settings,
  public.clients,
  public.client_addresses,
  public.catalog_items,
  public.invoice_records
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.profiles enable row level security;
alter table public.business_settings enable row level security;
alter table public.clients enable row level security;
alter table public.client_addresses enable row level security;
alter table public.catalog_items enable row level security;
alter table public.invoice_records enable row level security;

create policy "profiles owner select" on public.profiles for select to authenticated using (id = auth.uid());
create policy "profiles owner insert" on public.profiles for insert to authenticated with check (id = auth.uid());
create policy "profiles owner update" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "profiles owner delete" on public.profiles for delete to authenticated using (id = auth.uid());

create policy "business settings owner all" on public.business_settings for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "clients owner all" on public.clients for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "client addresses owner select" on public.client_addresses for select to authenticated
  using (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()));
create policy "client addresses owner insert" on public.client_addresses for insert to authenticated
  with check (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()));
create policy "client addresses owner update" on public.client_addresses for update to authenticated
  using (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()))
  with check (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()));
create policy "client addresses owner delete" on public.client_addresses for delete to authenticated
  using (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()));

create policy "catalog items owner all" on public.catalog_items for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "invoice records owner all" on public.invoice_records for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
"""


async def build_legacy_schema(url: str) -> None:
    conn = await asyncpg.connect(asyncpg_dsn(url))
    try:
        await conn.execute(LEGACY_SCHEMA_SQL)
    finally:
        await conn.close()
