"""Reconstruct database shapes that existed before Alembic was adopted.

``build_legacy_schema`` mirrors the older ``0001_baseline`` shape.
``build_pre_alembic_head_schema`` separately executes an isolated transcription
of the final historical SQLAlchemy ``metadata.create_all`` models plus runtime
DDL. Keeping those paths distinct prevents canonical SQL from masking the drift
that the adoption migrations must repair.
"""

from __future__ import annotations

import asyncpg
from sqlalchemy import (
    CheckConstraint,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.ext.asyncio import create_async_engine

from tests.support.postgres import asyncpg_dsn

LEGACY_SCHEMA_SQL = """
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.business_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text,
  address text,
  email text,
  phone text,
  tax_id text,
  logo_path text,
  default_currency text not null default 'USD',
  default_tax_pct double precision not null default 0.0,
  payment_terms text not null default 'Net 30',
  bank_name text,
  account_name text,
  account_number text,
  routing_number text,
  payment_notes text,
  updated_at timestamptz not null default now(),
  constraint uq_business_settings_user_id unique (user_id)
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  address text,
  email text,
  phone text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.client_addresses (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  label text,
  address text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.catalog_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  description text not null,
  unit_price double precision not null default 0.0,
  unit text not null default 'item',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoice_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  filename text not null,
  file_path text not null,
  source text not null,
  invoice_number text,
  client_name text,
  issue_date text,
  grand_total double precision,
  currency text not null default 'USD',
  chroma_doc_id text,
  status text not null default 'draft',
  invoice_json text,
  created_at timestamptz not null default now(),
  constraint valid_source check (source in ('uploaded', 'generated'))
);

create index if not exists ix_profiles_email on public.profiles(email);
create index if not exists ix_business_settings_user_id on public.business_settings(user_id);
create index if not exists ix_clients_user_id on public.clients(user_id);
create index if not exists ix_clients_name on public.clients(name);
create index if not exists ix_client_addresses_client_id on public.client_addresses(client_id);
create index if not exists ix_catalog_items_user_id on public.catalog_items(user_id);
create index if not exists ix_catalog_items_description on public.catalog_items(description);
create index if not exists ix_invoice_records_user_id on public.invoice_records(user_id);
create index if not exists ix_invoice_records_invoice_number on public.invoice_records(invoice_number);
create index if not exists ix_invoice_records_client_name on public.invoice_records(client_name);

grant select, insert, update, delete on table
  public.profiles,
  public.business_settings,
  public.clients,
  public.client_addresses,
  public.catalog_items,
  public.invoice_records
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.profiles enable row level security;
alter table public.business_settings enable row level security;
alter table public.clients enable row level security;
alter table public.client_addresses enable row level security;
alter table public.catalog_items enable row level security;
alter table public.invoice_records enable row level security;

create policy "profiles owner select" on public.profiles for select to authenticated using (id = auth.uid());
create policy "profiles owner insert" on public.profiles for insert to authenticated with check (id = auth.uid());
create policy "profiles owner update" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "profiles owner delete" on public.profiles for delete to authenticated using (id = auth.uid());

create policy "business settings owner all" on public.business_settings for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "clients owner all" on public.clients for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "client addresses owner select" on public.client_addresses for select to authenticated
  using (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()));
create policy "client addresses owner insert" on public.client_addresses for insert to authenticated
  with check (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()));
create policy "client addresses owner update" on public.client_addresses for update to authenticated
  using (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()))
  with check (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()));
create policy "client addresses owner delete" on public.client_addresses for delete to authenticated
  using (exists (select 1 from public.clients where clients.id = client_addresses.client_id and clients.user_id = auth.uid()));

create policy "catalog items owner all" on public.catalog_items for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "invoice records owner all" on public.invoice_records for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
"""


async def build_legacy_schema(url: str) -> None:
    conn = await asyncpg.connect(asyncpg_dsn(url))
    try:
        await conn.execute(LEGACY_SCHEMA_SQL)
    finally:
        await conn.close()


# This is a direct, isolated transcription of the SQLAlchemy metadata and
# runtime SQL at commit a51f3a4, the final pre-Alembic startup path. It must not
# inherit the canonical SQL's RLS, policies, grants, types, or FK semantics:
# those are exactly what adoption must repair.
def _pre_alembic_runtime_metadata() -> MetaData:
    metadata = MetaData()
    Table(
        "profiles",
        metadata,
        Column("id", PGUUID(as_uuid=False), primary_key=True),
        Column("email", String, nullable=False, unique=True, index=True),
        Column("display_name", String),
        Column("created_at", DateTime, nullable=False),
    )
    Table(
        "business_settings",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("user_id", PGUUID(as_uuid=False), ForeignKey("profiles.id"), nullable=False, index=True),
        Column("name", String),
        Column("address", Text),
        Column("email", String),
        Column("phone", String),
        Column("tax_id", String),
        Column("logo_path", String),
        Column("default_currency", String, nullable=False),
        Column("default_tax_pct", Float, nullable=False),
        Column("payment_terms", String, nullable=False),
        Column("bank_name", String),
        Column("account_name", String),
        Column("account_number", String),
        Column("routing_number", String),
        Column("payment_notes", Text),
        Column("updated_at", DateTime, nullable=False),
        UniqueConstraint("user_id", name="uq_business_settings_user_id"),
    )
    Table(
        "clients",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("user_id", PGUUID(as_uuid=False), ForeignKey("profiles.id"), nullable=False, index=True),
        Column("name", String, nullable=False, index=True),
        Column("client_code", String(32), index=True),
        Column("address", Text),
        Column("email", String),
        Column("phone", String),
        Column("notes", Text),
        Column("created_at", DateTime, nullable=False),
        Column("updated_at", DateTime, nullable=False),
        UniqueConstraint("user_id", "client_code", name="uq_clients_user_id_client_code"),
    )
    Table(
        "client_addresses",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("user_id", PGUUID(as_uuid=False), ForeignKey("profiles.id"), nullable=False, index=True),
        Column("client_id", Integer, ForeignKey("clients.id", ondelete="CASCADE"), nullable=False, index=True),
        Column("label", String),
        Column("address", Text, nullable=False),
        Column("created_at", DateTime, nullable=False),
    )
    Table(
        "catalog_items",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("user_id", PGUUID(as_uuid=False), ForeignKey("profiles.id"), nullable=False, index=True),
        Column("description", String, nullable=False, index=True),
        Column("unit_price", Float, nullable=False),
        Column("unit", String, nullable=False),
        Column("notes", Text),
        Column("created_at", DateTime, nullable=False),
        Column("updated_at", DateTime, nullable=False),
    )
    Table(
        "invoice_records",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("user_id", PGUUID(as_uuid=False), ForeignKey("profiles.id"), nullable=False, index=True),
        Column("client_id", Integer, ForeignKey("clients.id", ondelete="SET NULL"), index=True),
        Column("client_invoice_sequence", Integer),
        Column("filename", String, nullable=False),
        Column("file_path", String, nullable=False),
        Column("storage_path", String),
        Column("source", String, nullable=False),
        Column("invoice_number", String, index=True),
        Column("client_name", String, index=True),
        Column("issue_date", String),
        Column("grand_total", Float),
        Column("currency", String, nullable=False),
        Column("rag_doc_id", String),
        Column("status", String, nullable=False),
        Column("invoice_json", Text),
        Column("created_at", DateTime, nullable=False),
        CheckConstraint("source IN ('uploaded', 'generated')", name="valid_source"),
        UniqueConstraint(
            "user_id",
            "client_id",
            "client_invoice_sequence",
            name="uq_invoice_records_user_client_sequence",
        ),
    )
    Table(
        "invoice_emails",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("user_id", PGUUID(as_uuid=False), ForeignKey("profiles.id"), nullable=False, index=True),
        Column("invoice_record_id", Integer, ForeignKey("invoice_records.id", ondelete="CASCADE"), nullable=False, index=True),
        Column("recipient_email", String, nullable=False),
        Column("cc_email", String),
        Column("subject", String, nullable=False),
        Column("message_body", Text, nullable=False),
        Column("status", String, nullable=False),
        Column("provider", String, nullable=False),
        Column("provider_message_id", String),
        Column("error_message", Text),
        Column("sent_at", DateTime),
        Column("created_at", DateTime, nullable=False),
    )
    return metadata


PRE_ALEMBIC_RUNTIME_SQL = """
create extension if not exists vector with schema extensions;

update public.client_addresses as ca
   set user_id = c.user_id
  from public.clients as c
 where ca.client_id = c.id and ca.user_id is null and c.user_id is not null;

create table if not exists public.invoice_embeddings (
  id bigserial primary key,
  doc_id uuid not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  invoice_record_id bigint not null references public.invoice_records(id) on delete cascade,
  filename text not null,
  chunk_index integer not null,
  content text not null,
  embedding extensions.vector(1536) not null,
  created_at timestamp without time zone not null default now(),
  constraint uq_invoice_embeddings_doc_chunk unique (doc_id, chunk_index)
);

create index if not exists idx_invoice_embeddings_user_id on public.invoice_embeddings(user_id);
create index if not exists idx_invoice_embeddings_record_id on public.invoice_embeddings(invoice_record_id);
create index if not exists idx_client_addresses_user_id on public.client_addresses(user_id);
create index if not exists idx_invoice_emails_user_id on public.invoice_emails(user_id);
create index if not exists idx_invoice_emails_record_id on public.invoice_emails(invoice_record_id);
create index if not exists idx_invoice_embeddings_embedding_hnsw
  on public.invoice_embeddings using hnsw (embedding vector_cosine_ops);
"""


async def build_pre_alembic_head_schema(url: str) -> None:
    """Execute the historical metadata.create_all + runtime-DDL startup path."""
    from tests.support.postgres import bootstrap_supabase_stubs

    await bootstrap_supabase_stubs(url)
    engine = create_async_engine(url)
    try:
        async with engine.begin() as conn:
            await conn.run_sync(_pre_alembic_runtime_metadata().create_all)
    finally:
        await engine.dispose()

    conn = await asyncpg.connect(asyncpg_dsn(url))
    try:
        await conn.execute(PRE_ALEMBIC_RUNTIME_SQL)
    finally:
        await conn.close()
