"""Supabase-native RAG storage, per-user addresses, and invoice email history.

Brings the schema to its current shape:

* invoice vectors move into pgvector-backed ``invoice_embeddings``, so the
  legacy Chroma document id becomes ``rag_doc_id``;
* ``client_addresses`` gains direct user ownership (backfilled from its
  client) so address queries no longer depend on a join to prove tenancy;
* invoice PDFs record their Supabase Storage path;
* ``invoice_emails`` records delivery history.

Statements are written defensively because deployments that ran the old
startup DDL may already have some of these objects.

Revision ID: 0003_rag_and_email
Revises: 0002_client_numbering
"""

from alembic import op

revision = "0003_rag_and_email"
down_revision = "0002_client_numbering"
branch_labels = None
depends_on = None

# The old startup DDL performed this rename too, so tolerate either name.
RENAME_DOC_ID = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'invoice_records'
          AND column_name = 'chroma_doc_id'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'invoice_records'
          AND column_name = 'rag_doc_id'
    ) THEN
        ALTER TABLE public.invoice_records RENAME COLUMN chroma_doc_id TO rag_doc_id;
    END IF;
END $$
"""

REVERT_DOC_ID = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'invoice_records'
          AND column_name = 'rag_doc_id'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'invoice_records'
          AND column_name = 'chroma_doc_id'
    ) THEN
        ALTER TABLE public.invoice_records RENAME COLUMN rag_doc_id TO chroma_doc_id;
    END IF;
END $$
"""

UPGRADE = (
    "create extension if not exists vector with schema extensions",
    RENAME_DOC_ID,
    "alter table public.invoice_records add column if not exists rag_doc_id text",
    "alter table public.invoice_records add column if not exists storage_path text",
    "alter table public.client_addresses add column if not exists user_id uuid",
    # Every address inherits the owner of its client before ownership is enforced.
    """
    update public.client_addresses as ca
       set user_id = c.user_id
      from public.clients as c
     where ca.client_id = c.id
       and ca.user_id is null
    """,
    "alter table public.client_addresses alter column user_id set not null",
    "alter table public.client_addresses drop constraint if exists client_addresses_user_id_fkey",
    """
    alter table public.client_addresses
      add constraint client_addresses_user_id_fkey
      foreign key (user_id) references public.profiles(id) on delete cascade
    """,
    """
    create table if not exists public.invoice_embeddings (
      id bigint generated by default as identity primary key,
      doc_id uuid not null,
      user_id uuid not null references public.profiles(id) on delete cascade,
      invoice_record_id bigint not null references public.invoice_records(id) on delete cascade,
      filename text not null,
      chunk_index integer not null,
      content text not null,
      embedding extensions.vector(1536) not null,
      created_at timestamptz not null default now(),
      constraint uq_invoice_embeddings_doc_chunk unique (doc_id, chunk_index)
    )
    """,
    """
    create table if not exists public.invoice_emails (
      id bigint generated by default as identity primary key,
      user_id uuid not null references public.profiles(id) on delete cascade,
      invoice_record_id bigint not null references public.invoice_records(id) on delete cascade,
      recipient_email text not null,
      cc_email text,
      subject text not null,
      message_body text not null,
      status text not null default 'pending',
      provider text not null default 'smtp',
      provider_message_id text,
      error_message text,
      sent_at timestamptz,
      created_at timestamptz not null default now()
    )
    """,
    "create index if not exists ix_client_addresses_user_id on public.client_addresses(user_id)",
    "create index if not exists ix_invoice_embeddings_user_id on public.invoice_embeddings(user_id)",
    "create index if not exists ix_invoice_embeddings_record_id on public.invoice_embeddings(invoice_record_id)",
    """
    create index if not exists ix_invoice_embeddings_embedding_hnsw
      on public.invoice_embeddings using hnsw (embedding vector_cosine_ops)
    """,
    "create index if not exists ix_invoice_emails_user_id on public.invoice_emails(user_id)",
    "create index if not exists ix_invoice_emails_record_id on public.invoice_emails(invoice_record_id)",
    """
    grant select, insert, update, delete on table
      public.invoice_embeddings,
      public.invoice_emails
      to authenticated
    """,
    # Re-run so the sequences behind the new identity columns are covered.
    "grant usage, select on all sequences in schema public to authenticated",
    "alter table public.invoice_embeddings enable row level security",
    "alter table public.invoice_emails enable row level security",
    'drop policy if exists "invoice embeddings owner all" on public.invoice_embeddings',
    """
    create policy "invoice embeddings owner all" on public.invoice_embeddings for all to authenticated
      using (user_id = auth.uid())
      with check (user_id = auth.uid())
    """,
    'drop policy if exists "invoice emails owner all" on public.invoice_emails',
    """
    create policy "invoice emails owner all" on public.invoice_emails for all to authenticated
      using (user_id = auth.uid())
      with check (user_id = auth.uid())
    """,
)

DOWNGRADE = (
    "drop table if exists public.invoice_emails cascade",
    "drop table if exists public.invoice_embeddings cascade",
    "drop index if exists public.ix_client_addresses_user_id",
    "alter table public.client_addresses drop column if exists user_id",
    "alter table public.invoice_records drop column if exists storage_path",
    REVERT_DOC_ID,
)


def upgrade() -> None:
    for statement in UPGRADE:
        op.execute(statement)


def downgrade() -> None:
    for statement in DOWNGRADE:
        op.execute(statement)
