"""Normalize databases adopted from the pre-Alembic runtime DDL.

Deployments that were stamped at ``0003_rag_and_email`` could still retain
structural drift because ``stamp`` records a revision without executing SQL.
This revision converges the actual historical ``Base.metadata.create_all`` plus
runtime-DDL shape on the schema produced by a clean migration/bootstrap.

Revision ID: 0004_normalize_adopted_schema
Revises: 0003_rag_and_email
"""

from alembic import op

revision = "0004_normalize_adopted_schema"
down_revision = "0003_rag_and_email"
branch_labels = None
depends_on = None


IDENTITY_TABLES = (
    "business_settings",
    "clients",
    "client_addresses",
    "catalog_items",
    "invoice_records",
    "invoice_embeddings",
    "invoice_emails",
)


def _normalize_identity(table: str) -> str:
    return f"""
    DO $$
    DECLARE next_value bigint;
    DECLARE sequence_name text;
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = '{table}'
           AND column_name = 'id' AND is_identity = 'YES'
      ) THEN
        SELECT coalesce(max(id), 0) + 1 INTO next_value FROM public.{table};
        ALTER TABLE public.{table} ALTER COLUMN id DROP DEFAULT;
        DROP SEQUENCE IF EXISTS public.{table}_id_seq CASCADE;
        ALTER TABLE public.{table} ALTER COLUMN id TYPE bigint USING id::bigint;
        ALTER TABLE public.{table}
          ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        sequence_name := pg_get_serial_sequence('public.{table}', 'id');
        EXECUTE format('ALTER SEQUENCE %s RESTART WITH %s', sequence_name, next_value);
      END IF;
    END $$
    """


def _normalize_timestamp(table: str, column: str) -> str:
    return f"""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'public' AND table_name = '{table}'
           AND column_name = '{column}'
           AND data_type = 'timestamp without time zone'
      ) THEN
        ALTER TABLE public.{table}
          ALTER COLUMN {column} TYPE timestamptz
          USING {column} AT TIME ZONE 'UTC';
      END IF;
    END $$
    """


TIMESTAMP_COLUMNS = (
    ("profiles", "created_at"),
    ("business_settings", "updated_at"),
    ("clients", "created_at"),
    ("clients", "updated_at"),
    ("client_addresses", "created_at"),
    ("catalog_items", "created_at"),
    ("catalog_items", "updated_at"),
    ("invoice_records", "created_at"),
    ("invoice_embeddings", "created_at"),
    ("invoice_emails", "sent_at"),
    ("invoice_emails", "created_at"),
)


DROP_DEPENDENT_CONSTRAINTS = (
    "alter table public.profiles drop constraint if exists profiles_id_fkey",
    "alter table public.profiles drop constraint if exists profiles_email_key",
    "alter table public.business_settings drop constraint if exists business_settings_user_id_fkey",
    "alter table public.clients drop constraint if exists clients_user_id_fkey",
    "alter table public.client_addresses drop constraint if exists client_addresses_user_id_fkey",
    "alter table public.client_addresses drop constraint if exists client_addresses_client_id_fkey",
    "alter table public.catalog_items drop constraint if exists catalog_items_user_id_fkey",
    "alter table public.invoice_records drop constraint if exists invoice_records_user_id_fkey",
    "alter table public.invoice_records drop constraint if exists invoice_records_client_id_fkey",
    "alter table public.invoice_records drop constraint if exists valid_source",
    "alter table public.invoice_embeddings drop constraint if exists invoice_embeddings_user_id_fkey",
    "alter table public.invoice_embeddings drop constraint if exists invoice_embeddings_invoice_record_id_fkey",
    "alter table public.invoice_emails drop constraint if exists invoice_emails_user_id_fkey",
    "alter table public.invoice_emails drop constraint if exists invoice_emails_invoice_record_id_fkey",
    "alter table public.clients drop constraint if exists uq_clients_user_id_client_code",
    "alter table public.invoice_records drop constraint if exists uq_invoice_records_user_client_sequence",
    "drop index if exists public.uq_clients_user_id_client_code",
    "drop index if exists public.uq_invoice_records_user_client_sequence",
    "drop index if exists public.ix_profiles_email",
)


NORMALIZE_COLUMN_TYPES = (
    """
    alter table public.profiles
      alter column email type text,
      alter column display_name type text
    """,
    """
    alter table public.business_settings
      alter column name type text,
      alter column email type text,
      alter column phone type text,
      alter column tax_id type text,
      alter column logo_path type text,
      alter column default_currency type text,
      alter column payment_terms type text,
      alter column bank_name type text,
      alter column account_name type text,
      alter column account_number type text,
      alter column routing_number type text
    """,
    """
    alter table public.clients
      alter column name type text,
      alter column client_code type text,
      alter column email type text,
      alter column phone type text
    """,
    """
    alter table public.client_addresses
      alter column client_id type bigint using client_id::bigint,
      alter column label type text
    """,
    """
    alter table public.catalog_items
      alter column description type text,
      alter column unit type text
    """,
    """
    alter table public.invoice_records
      alter column client_id type bigint using client_id::bigint,
      alter column filename type text,
      alter column file_path type text,
      alter column storage_path type text,
      alter column source type text,
      alter column invoice_number type text,
      alter column client_name type text,
      alter column issue_date type text,
      alter column currency type text,
      alter column rag_doc_id type text,
      alter column status type text
    """,
    """
    alter table public.invoice_emails
      alter column invoice_record_id type bigint using invoice_record_id::bigint,
      alter column recipient_email type text,
      alter column cc_email type text,
      alter column subject type text,
      alter column status type text,
      alter column provider type text,
      alter column provider_message_id type text
    """,
)


SET_DEFAULTS = (
    "alter table public.profiles alter column created_at set default now()",
    """
    alter table public.business_settings
      alter column default_currency set default 'USD',
      alter column default_tax_pct set default 0.0,
      alter column payment_terms set default 'Net 30',
      alter column updated_at set default now()
    """,
    """
    alter table public.clients
      alter column created_at set default now(),
      alter column updated_at set default now()
    """,
    "alter table public.client_addresses alter column created_at set default now()",
    """
    alter table public.catalog_items
      alter column unit_price set default 0.0,
      alter column unit set default 'item',
      alter column created_at set default now(),
      alter column updated_at set default now()
    """,
    """
    alter table public.invoice_records
      alter column currency set default 'USD',
      alter column status set default 'draft',
      alter column created_at set default now()
    """,
)


ADD_CANONICAL_CONSTRAINTS = (
    """
    alter table public.profiles add constraint profiles_id_fkey
      foreign key (id) references auth.users(id) on delete cascade
    """,
    "alter table public.profiles add constraint profiles_email_key unique (email)",
    """
    alter table public.business_settings add constraint business_settings_user_id_fkey
      foreign key (user_id) references public.profiles(id) on delete cascade
    """,
    """
    alter table public.clients add constraint clients_user_id_fkey
      foreign key (user_id) references public.profiles(id) on delete cascade
    """,
    """
    alter table public.client_addresses add constraint client_addresses_user_id_fkey
      foreign key (user_id) references public.profiles(id) on delete cascade
    """,
    """
    alter table public.client_addresses add constraint client_addresses_client_id_fkey
      foreign key (client_id) references public.clients(id) on delete cascade
    """,
    """
    alter table public.catalog_items add constraint catalog_items_user_id_fkey
      foreign key (user_id) references public.profiles(id) on delete cascade
    """,
    """
    alter table public.invoice_records add constraint invoice_records_user_id_fkey
      foreign key (user_id) references public.profiles(id) on delete cascade
    """,
    """
    alter table public.invoice_records add constraint invoice_records_client_id_fkey
      foreign key (client_id) references public.clients(id) on delete set null
    """,
    """
    alter table public.invoice_records add constraint valid_source
      check (source in ('uploaded', 'generated'))
    """,
    """
    alter table public.invoice_embeddings add constraint invoice_embeddings_user_id_fkey
      foreign key (user_id) references public.profiles(id) on delete cascade
    """,
    """
    alter table public.invoice_embeddings add constraint invoice_embeddings_invoice_record_id_fkey
      foreign key (invoice_record_id) references public.invoice_records(id) on delete cascade
    """,
    """
    alter table public.invoice_emails add constraint invoice_emails_user_id_fkey
      foreign key (user_id) references public.profiles(id) on delete cascade
    """,
    """
    alter table public.invoice_emails add constraint invoice_emails_invoice_record_id_fkey
      foreign key (invoice_record_id) references public.invoice_records(id) on delete cascade
    """,
    """
    alter table public.clients add constraint uq_clients_user_id_client_code
      unique (user_id, client_code)
    """,
    """
    alter table public.invoice_records add constraint uq_invoice_records_user_client_sequence
      unique (user_id, client_id, client_invoice_sequence)
    """,
)


INDEXES = (
    "create index if not exists ix_profiles_email on public.profiles(email)",
    "drop index if exists public.idx_client_addresses_user_id",
    "drop index if exists public.idx_invoice_embeddings_user_id",
    "drop index if exists public.idx_invoice_embeddings_record_id",
    "drop index if exists public.idx_invoice_embeddings_embedding_hnsw",
    "drop index if exists public.idx_invoice_emails_user_id",
    "drop index if exists public.idx_invoice_emails_record_id",
    "drop index if exists public.ix_invoice_emails_invoice_record_id",
    "create index if not exists ix_client_addresses_user_id on public.client_addresses(user_id)",
    "create index if not exists ix_invoice_embeddings_user_id on public.invoice_embeddings(user_id)",
    "create index if not exists ix_invoice_embeddings_record_id on public.invoice_embeddings(invoice_record_id)",
    """
    create index if not exists ix_invoice_embeddings_embedding_hnsw
      on public.invoice_embeddings using hnsw (embedding vector_cosine_ops)
    """,
    "create index if not exists ix_invoice_emails_user_id on public.invoice_emails(user_id)",
    "create index if not exists ix_invoice_emails_record_id on public.invoice_emails(invoice_record_id)",
)


TABLES = (
    "profiles",
    "business_settings",
    "clients",
    "client_addresses",
    "catalog_items",
    "invoice_records",
    "invoice_embeddings",
    "invoice_emails",
)


DROP_POLICIES = (
    'drop policy if exists "profiles owner select" on public.profiles',
    'drop policy if exists "profiles owner insert" on public.profiles',
    'drop policy if exists "profiles owner update" on public.profiles',
    'drop policy if exists "profiles owner delete" on public.profiles',
    'drop policy if exists "business settings owner all" on public.business_settings',
    'drop policy if exists "clients owner all" on public.clients',
    'drop policy if exists "client addresses owner select" on public.client_addresses',
    'drop policy if exists "client addresses owner insert" on public.client_addresses',
    'drop policy if exists "client addresses owner update" on public.client_addresses',
    'drop policy if exists "client addresses owner delete" on public.client_addresses',
    'drop policy if exists "catalog items owner all" on public.catalog_items',
    'drop policy if exists "invoice records owner all" on public.invoice_records',
    'drop policy if exists "invoice embeddings owner all" on public.invoice_embeddings',
    'drop policy if exists "invoice emails owner all" on public.invoice_emails',
)


POLICIES = (
    'drop policy if exists "profiles owner select" on public.profiles',
    'drop policy if exists "profiles owner insert" on public.profiles',
    'drop policy if exists "profiles owner update" on public.profiles',
    'drop policy if exists "profiles owner delete" on public.profiles',
    'create policy "profiles owner select" on public.profiles for select to authenticated using (id = auth.uid())',
    'create policy "profiles owner insert" on public.profiles for insert to authenticated with check (id = auth.uid())',
    'create policy "profiles owner update" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid())',
    'create policy "profiles owner delete" on public.profiles for delete to authenticated using (id = auth.uid())',
    'drop policy if exists "business settings owner all" on public.business_settings',
    """
    create policy "business settings owner all" on public.business_settings
      for all to authenticated using (user_id = auth.uid())
      with check (user_id = auth.uid())
    """,
    'drop policy if exists "clients owner all" on public.clients',
    """
    create policy "clients owner all" on public.clients
      for all to authenticated using (user_id = auth.uid())
      with check (user_id = auth.uid())
    """,
    'drop policy if exists "client addresses owner select" on public.client_addresses',
    'drop policy if exists "client addresses owner insert" on public.client_addresses',
    'drop policy if exists "client addresses owner update" on public.client_addresses',
    'drop policy if exists "client addresses owner delete" on public.client_addresses',
    """
    create policy "client addresses owner select" on public.client_addresses
      for select to authenticated using (exists (
        select 1 from public.clients
         where clients.id = client_addresses.client_id
           and clients.user_id = auth.uid()
      ))
    """,
    """
    create policy "client addresses owner insert" on public.client_addresses
      for insert to authenticated with check (exists (
        select 1 from public.clients
         where clients.id = client_addresses.client_id
           and clients.user_id = auth.uid()
      ))
    """,
    """
    create policy "client addresses owner update" on public.client_addresses
      for update to authenticated using (exists (
        select 1 from public.clients
         where clients.id = client_addresses.client_id
           and clients.user_id = auth.uid()
      )) with check (exists (
        select 1 from public.clients
         where clients.id = client_addresses.client_id
           and clients.user_id = auth.uid()
      ))
    """,
    """
    create policy "client addresses owner delete" on public.client_addresses
      for delete to authenticated using (exists (
        select 1 from public.clients
         where clients.id = client_addresses.client_id
           and clients.user_id = auth.uid()
      ))
    """,
    'drop policy if exists "catalog items owner all" on public.catalog_items',
    """
    create policy "catalog items owner all" on public.catalog_items
      for all to authenticated using (user_id = auth.uid())
      with check (user_id = auth.uid())
    """,
    'drop policy if exists "invoice records owner all" on public.invoice_records',
    """
    create policy "invoice records owner all" on public.invoice_records
      for all to authenticated using (user_id = auth.uid())
      with check (user_id = auth.uid())
    """,
    'drop policy if exists "invoice embeddings owner all" on public.invoice_embeddings',
    """
    create policy "invoice embeddings owner all" on public.invoice_embeddings
      for all to authenticated using (user_id = auth.uid())
      with check (user_id = auth.uid())
    """,
    'drop policy if exists "invoice emails owner all" on public.invoice_emails',
    """
    create policy "invoice emails owner all" on public.invoice_emails
      for all to authenticated using (user_id = auth.uid())
      with check (user_id = auth.uid())
    """,
)


GRANTS = (
    """
    revoke all on table
      public.profiles, public.business_settings, public.clients,
      public.client_addresses, public.catalog_items, public.invoice_records,
      public.invoice_embeddings, public.invoice_emails
      from authenticated
    """,
    """
    grant select, insert, update, delete on table
      public.profiles, public.business_settings, public.clients,
      public.client_addresses, public.catalog_items, public.invoice_records,
      public.invoice_embeddings, public.invoice_emails
      to authenticated
    """,
    """
    revoke all on sequence
      public.business_settings_id_seq, public.clients_id_seq,
      public.client_addresses_id_seq, public.catalog_items_id_seq,
      public.invoice_records_id_seq, public.invoice_embeddings_id_seq,
      public.invoice_emails_id_seq
      from authenticated
    """,
    """
    grant usage, select on sequence
      public.business_settings_id_seq, public.clients_id_seq,
      public.client_addresses_id_seq, public.catalog_items_id_seq,
      public.invoice_records_id_seq, public.invoice_embeddings_id_seq,
      public.invoice_emails_id_seq
      to authenticated
    """,
)


def upgrade() -> None:
    op.execute(
        """
        update public.client_addresses as ca
           set user_id = c.user_id
          from public.clients as c
         where ca.client_id = c.id and ca.user_id is null
        """
    )
    op.execute("alter table public.client_addresses alter column user_id set not null")

    for statement in DROP_DEPENDENT_CONSTRAINTS:
        op.execute(statement)
    for statement in DROP_POLICIES:
        op.execute(statement)
    for table in IDENTITY_TABLES:
        op.execute(_normalize_identity(table))
    for statement in NORMALIZE_COLUMN_TYPES:
        op.execute(statement)
    for table, column in TIMESTAMP_COLUMNS:
        op.execute(_normalize_timestamp(table, column))
    for statement in SET_DEFAULTS:
        op.execute(statement)
    for statement in ADD_CANONICAL_CONSTRAINTS:
        op.execute(statement)
    for statement in INDEXES:
        op.execute(statement)
    for table in TABLES:
        op.execute(f"alter table public.{table} enable row level security")
    for statement in POLICIES:
        op.execute(statement)
    for statement in GRANTS:
        op.execute(statement)


def downgrade() -> None:
    # Restoring deployment-specific drift would discard guarantees rather than
    # roll back application behavior. Earlier revisions remain traversable after
    # this no-op boundary.
    pass
